
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pf_Clave_Usuario = new javax.swing.JPasswordField();
        tf_Usuario = new javax.swing.JTextField();
        bt_Login = new javax.swing.JButton();
        jd_Crear_Serie = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        bt_Crear_Serie = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_Nombre_Serie = new javax.swing.JTextField();
        tf_Temporada = new javax.swing.JTextField();
        tf_Duracion_Serie = new javax.swing.JTextField();
        tf_Productora_Serie = new javax.swing.JTextField();
        bt_Crear_Guardar = new javax.swing.JButton();
        rb_Subtitulos_No = new javax.swing.JRadioButton();
        rb_Español = new javax.swing.JRadioButton();
        rb_Ingles = new javax.swing.JRadioButton();
        rb_Sitcom = new javax.swing.JRadioButton();
        rb_Drama = new javax.swing.JRadioButton();
        rb_Novelas = new javax.swing.JRadioButton();
        rb_Aleman = new javax.swing.JRadioButton();
        rb_Doblaje_Si = new javax.swing.JRadioButton();
        rb_Subtitulos_Si = new javax.swing.JRadioButton();
        rb_Doblaje_No = new javax.swing.JRadioButton();
        rb_Frances = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Arctores_Series = new javax.swing.JTextArea();
        rb_Suspenso = new javax.swing.JRadioButton();
        rb_YYY = new javax.swing.JRadioButton();
        bg_Idioma_Serie = new javax.swing.ButtonGroup();
        bg_Categoria_Serie = new javax.swing.ButtonGroup();
        bg_Subtitulo_Serie = new javax.swing.ButtonGroup();
        bg_Doblaje_Serie = new javax.swing.ButtonGroup();
        jd_Crear_Pelicula = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_Nombre_Pelicula = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_Duracion_Pelicula = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rb_Terror = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_Arctores_Peliculas = new javax.swing.JTextArea();
        rb_Accion = new javax.swing.JRadioButton();
        rb_Romanticas = new javax.swing.JRadioButton();
        rb_Suspenso1 = new javax.swing.JRadioButton();
        rb_Ciencia_Ficcion = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        tf_Director = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_Productora_Pelicula = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rb_Español1 = new javax.swing.JRadioButton();
        rb_Ingles1 = new javax.swing.JRadioButton();
        rb_Aleman1 = new javax.swing.JRadioButton();
        rb_Frances1 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        rb_Doblaje_Si1 = new javax.swing.JRadioButton();
        rb_Doblaje_No1 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        rb_Subtitulos_Si1 = new javax.swing.JRadioButton();
        rb_Subtitulos_No1 = new javax.swing.JRadioButton();
        bt_Crear_Guardar1 = new javax.swing.JButton();
        bt_Crear_Pelicula = new javax.swing.JButton();
        rb_Animacion = new javax.swing.JRadioButton();
        rb_Fantacsia = new javax.swing.JRadioButton();
        jd_Listar = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_Catalogo = new javax.swing.JTree();
        bt_Cargar = new javax.swing.JButton();
        bg_Categoria_Pelicula = new javax.swing.ButtonGroup();
        bg_Doblaje_Pelicula = new javax.swing.ButtonGroup();
        bg_Subtitulado_Pelicula = new javax.swing.ButtonGroup();
        bg_Idioma_Pelicula = new javax.swing.ButtonGroup();
        jmb_Opciones = new javax.swing.JMenuBar();
        jm_Accerder = new javax.swing.JMenu();
        jmi_Login = new javax.swing.JMenuItem();
        jmi_Logout = new javax.swing.JMenuItem();
        jm_Series = new javax.swing.JMenu();
        jmi_Crear_Serie = new javax.swing.JMenuItem();
        jm_Peliculas = new javax.swing.JMenu();
        jmi_Crear_Pelicula = new javax.swing.JMenuItem();
        jm_Listar = new javax.swing.JMenu();
        jmi_Listar_Arbol = new javax.swing.JMenuItem();

        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Login de Usuario");

        jLabel3.setText("Contraseña");

        bt_Login.setText("Login");
        bt_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_LoginLayout = new javax.swing.GroupLayout(jd_Login.getContentPane());
        jd_Login.getContentPane().setLayout(jd_LoginLayout);
        jd_LoginLayout.setHorizontalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(jd_LoginLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_Usuario))
                        .addGroup(jd_LoginLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(pf_Clave_Usuario)))
                    .addComponent(bt_Login))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jd_LoginLayout.setVerticalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_Clave_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(bt_Login)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Creacion de Series");

        bt_Crear_Serie.setText("Crear");
        bt_Crear_Serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_SerieActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        jLabel6.setText("Tiempo de Duracion");

        jLabel7.setText("Actores Principales");

        jLabel8.setText("Temporadas");

        jLabel9.setText("Categoria");

        jLabel10.setText("Idioma Original");

        jLabel11.setText("Productora");

        jLabel12.setText("Doblaje");

        jLabel13.setText("Subtitulos");

        bt_Crear_Guardar.setText("Guardar");
        bt_Crear_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_GuardarActionPerformed(evt);
            }
        });

        bg_Subtitulo_Serie.add(rb_Subtitulos_No);
        rb_Subtitulos_No.setText("No");

        bg_Idioma_Serie.add(rb_Español);
        rb_Español.setText("Español");

        bg_Idioma_Serie.add(rb_Ingles);
        rb_Ingles.setText("Ingles");

        bg_Categoria_Serie.add(rb_Sitcom);
        rb_Sitcom.setText("Sitcom");

        bg_Categoria_Serie.add(rb_Drama);
        rb_Drama.setText("Drama");

        bg_Categoria_Serie.add(rb_Novelas);
        rb_Novelas.setText("Novelas");

        bg_Idioma_Serie.add(rb_Aleman);
        rb_Aleman.setText("Alemán");

        bg_Doblaje_Serie.add(rb_Doblaje_Si);
        rb_Doblaje_Si.setText("Si");

        bg_Subtitulo_Serie.add(rb_Subtitulos_Si);
        rb_Subtitulos_Si.setText("Si");

        bg_Doblaje_Serie.add(rb_Doblaje_No);
        rb_Doblaje_No.setText("No");

        bg_Idioma_Serie.add(rb_Frances);
        rb_Frances.setText("Francés");

        ta_Arctores_Series.setColumns(20);
        ta_Arctores_Series.setRows(5);
        jScrollPane1.setViewportView(ta_Arctores_Series);

        bg_Categoria_Serie.add(rb_Suspenso);
        rb_Suspenso.setText("Suspenso");

        bg_Categoria_Serie.add(rb_YYY);
        rb_YYY.setText("YYY");

        javax.swing.GroupLayout jd_Crear_SerieLayout = new javax.swing.GroupLayout(jd_Crear_Serie.getContentPane());
        jd_Crear_Serie.getContentPane().setLayout(jd_Crear_SerieLayout);
        jd_Crear_SerieLayout.setHorizontalGroup(
            jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Crear_SerieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addGroup(jd_Crear_SerieLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_Nombre_Serie))
                        .addGroup(jd_Crear_SerieLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_Duracion_Serie)))
                    .addGroup(jd_Crear_SerieLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Sitcom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Drama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Novelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_Suspenso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_YYY))
                    .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_SerieLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_Productora_Serie))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_SerieLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(tf_Temporada, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_Crear_SerieLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_Crear_SerieLayout.createSequentialGroup()
                        .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_SerieLayout.createSequentialGroup()
                                .addComponent(bt_Crear_Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_Crear_Serie))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_SerieLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Español))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_SerieLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Doblaje_Si)
                                .addGap(27, 27, 27)
                                .addComponent(rb_Doblaje_No))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_SerieLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_Subtitulos_Si)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Subtitulos_No)))
                        .addGap(21, 21, 21)
                        .addComponent(rb_Ingles)
                        .addGap(18, 18, 18)
                        .addComponent(rb_Aleman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Frances)))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jd_Crear_SerieLayout.setVerticalGroup(
            jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Crear_SerieLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_Nombre_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_Duracion_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rb_Sitcom)
                    .addComponent(rb_Drama)
                    .addComponent(rb_Novelas)
                    .addComponent(rb_Suspenso)
                    .addComponent(rb_YYY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_Temporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_Productora_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rb_Ingles)
                    .addComponent(rb_Aleman)
                    .addComponent(rb_Frances)
                    .addComponent(rb_Español))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rb_Doblaje_Si)
                    .addComponent(rb_Doblaje_No))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rb_Subtitulos_Si)
                    .addComponent(rb_Subtitulos_No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_Crear_SerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Guardar)
                    .addComponent(bt_Crear_Serie))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Creacion de Peliculas");

        jLabel15.setText("Nombre");

        jLabel16.setText("Tiempo de Duracion");

        jLabel17.setText("Categoria");

        bg_Categoria_Pelicula.add(rb_Terror);
        rb_Terror.setText("Terror");

        jLabel18.setText("Actores Principales");

        ta_Arctores_Peliculas.setColumns(20);
        ta_Arctores_Peliculas.setRows(5);
        jScrollPane2.setViewportView(ta_Arctores_Peliculas);

        bg_Categoria_Pelicula.add(rb_Accion);
        rb_Accion.setText("Accion");

        bg_Categoria_Pelicula.add(rb_Romanticas);
        rb_Romanticas.setText("Romanticas");

        bg_Categoria_Pelicula.add(rb_Suspenso1);
        rb_Suspenso1.setText("Suspenso");

        bg_Categoria_Pelicula.add(rb_Ciencia_Ficcion);
        rb_Ciencia_Ficcion.setText("Ciencia Ficcion");

        jLabel19.setText("Director");

        jLabel20.setText("Productora");

        jLabel21.setText("Idioma Original");

        bg_Idioma_Pelicula.add(rb_Español1);
        rb_Español1.setText("Español");

        bg_Idioma_Pelicula.add(rb_Ingles1);
        rb_Ingles1.setText("Ingles");

        bg_Idioma_Pelicula.add(rb_Aleman1);
        rb_Aleman1.setText("Alemán");

        bg_Idioma_Pelicula.add(rb_Frances1);
        rb_Frances1.setText("Francés");

        jLabel22.setText("Doblaje");

        bg_Doblaje_Pelicula.add(rb_Doblaje_Si1);
        rb_Doblaje_Si1.setText("Si");

        bg_Doblaje_Pelicula.add(rb_Doblaje_No1);
        rb_Doblaje_No1.setText("No");

        jLabel23.setText("Subtitulos");

        bg_Subtitulado_Pelicula.add(rb_Subtitulos_Si1);
        rb_Subtitulos_Si1.setText("Si");

        bg_Subtitulado_Pelicula.add(rb_Subtitulos_No1);
        rb_Subtitulos_No1.setText("No");

        bt_Crear_Guardar1.setText("Guardar");
        bt_Crear_Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_Guardar1ActionPerformed(evt);
            }
        });

        bt_Crear_Pelicula.setText("Crear");
        bt_Crear_Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_PeliculaActionPerformed(evt);
            }
        });

        bg_Categoria_Pelicula.add(rb_Animacion);
        rb_Animacion.setText("Animacion");

        bg_Categoria_Pelicula.add(rb_Fantacsia);
        rb_Fantacsia.setText("Fantasia");

        javax.swing.GroupLayout jd_Crear_PeliculaLayout = new javax.swing.GroupLayout(jd_Crear_Pelicula.getContentPane());
        jd_Crear_Pelicula.getContentPane().setLayout(jd_Crear_PeliculaLayout);
        jd_Crear_PeliculaLayout.setHorizontalGroup(
            jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14)
                        .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_Nombre_Pelicula))
                        .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_Duracion_Pelicula)))
                    .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Terror)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Accion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Romanticas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_Suspenso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_Ciencia_Ficcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Animacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_Fantacsia))
                    .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_PeliculaLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_Productora_Pelicula))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_PeliculaLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(tf_Director, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                        .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_PeliculaLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Español1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Crear_PeliculaLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Doblaje_Si1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_Doblaje_No1))
                            .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_Crear_Guardar1)
                                    .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_Subtitulos_Si1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Subtitulos_No1)
                                    .addComponent(bt_Crear_Pelicula))))
                        .addGap(21, 21, 21)
                        .addComponent(rb_Ingles1)
                        .addGap(18, 18, 18)
                        .addComponent(rb_Aleman1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Frances1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jd_Crear_PeliculaLayout.setVerticalGroup(
            jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Crear_PeliculaLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_Nombre_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_Duracion_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rb_Terror)
                    .addComponent(rb_Accion)
                    .addComponent(rb_Romanticas)
                    .addComponent(rb_Suspenso1)
                    .addComponent(rb_Ciencia_Ficcion)
                    .addComponent(rb_Animacion)
                    .addComponent(rb_Fantacsia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_Director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_Productora_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(rb_Ingles1)
                    .addComponent(rb_Aleman1)
                    .addComponent(rb_Frances1)
                    .addComponent(rb_Español1))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rb_Doblaje_Si1)
                    .addComponent(rb_Doblaje_No1))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rb_Subtitulos_Si1)
                    .addComponent(rb_Subtitulos_No1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_Crear_PeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Guardar1)
                    .addComponent(bt_Crear_Pelicula))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("mi_pc");
        jt_Catalogo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_Catalogo);

        bt_Cargar.setText("Cargar");
        bt_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ListarLayout = new javax.swing.GroupLayout(jd_Listar.getContentPane());
        jd_Listar.getContentPane().setLayout(jd_ListarLayout);
        jd_ListarLayout.setHorizontalGroup(
            jd_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jd_ListarLayout.createSequentialGroup()
                        .addComponent(bt_Cargar)
                        .addGap(0, 305, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_ListarLayout.setVerticalGroup(
            jd_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bt_Cargar))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nesflis");

        jm_Accerder.setText("Acceder");

        jmi_Login.setText("Login");
        jmi_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_LoginActionPerformed(evt);
            }
        });
        jm_Accerder.add(jmi_Login);

        jmi_Logout.setText("Login out");
        jmi_Logout.setEnabled(false);
        jm_Accerder.add(jmi_Logout);

        jmb_Opciones.add(jm_Accerder);

        jm_Series.setText("Series");
        jm_Series.setEnabled(false);

        jmi_Crear_Serie.setText("Crear Serie");
        jmi_Crear_Serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_Crear_SerieActionPerformed(evt);
            }
        });
        jm_Series.add(jmi_Crear_Serie);

        jmb_Opciones.add(jm_Series);

        jm_Peliculas.setText("Peliculas");
        jm_Peliculas.setEnabled(false);

        jmi_Crear_Pelicula.setText("Crear Pelicula");
        jmi_Crear_Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_Crear_PeliculaActionPerformed(evt);
            }
        });
        jm_Peliculas.add(jmi_Crear_Pelicula);

        jmb_Opciones.add(jm_Peliculas);

        jm_Listar.setText("Listar");
        jm_Listar.setEnabled(false);

        jmi_Listar_Arbol.setText("Listar en el Arbol");
        jmi_Listar_Arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_Listar_ArbolActionPerformed(evt);
            }
        });
        jm_Listar.add(jmi_Listar_Arbol);

        jmb_Opciones.add(jm_Listar);

        setJMenuBar(jmb_Opciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_LoginActionPerformed
        // TODO add your handling code here:
        jd_Login.setModal(true);
        jd_Login.pack();
        jd_Login.setLocationRelativeTo(this);
        jd_Login.setVisible(true);
    }//GEN-LAST:event_jmi_LoginActionPerformed

    private void bt_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LoginActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        String aux2 = "";
        File archivo;
        FileReader rf = null;
        BufferedReader br = null;
        try {
            archivo = new File("./registrados.txt");
            rf = new FileReader(archivo);
            br = new BufferedReader(rf);
            String linea;
            while ((linea = br.readLine()) != null) {
                for (int i = 0; i < linea.length(); i++) {
                    if (linea.charAt(i) == ';') {
                        cont++;
                        aux2 = linea;
                    }
                    if (cont == 3) {
                        String[] aux = aux2.split(";");
                        if (aux[0].equals(tf_Usuario.getText()) && aux[2].equals(pf_Clave_Usuario.getText())) {
                            bitacora += aux[0];
                            jmi_Login.setEnabled(false);
                            jm_Series.setEnabled(true);
                            jm_Peliculas.setEnabled(true);
                            jm_Listar.setEnabled(true);
                            jmi_Logout.setEnabled(true);
                            tf_Usuario.setText("");
                            pf_Clave_Usuario.setText("");
                            jd_Login.dispose();
                            cont = 0;
                        }
                    }

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            rf.close();
        } catch (IOException e) {
        }

    }//GEN-LAST:event_bt_LoginActionPerformed

    private void bt_Crear_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_GuardarActionPerformed
        // TODO add your handling code here:
        try {
            AMDS ap = new AMDS("LAB-6-JasonDeras\\lab6\\Nesflis\\Series");
            ap.cargarArchivo();
            String nombre;
            int duracion;
            String categoria;
            ArrayList actores = new ArrayList();
            int temporadoas;
            String productora;
            String idioma;
            String doblaje;
            String subtitulos;

            //If de los idiomas
            if (rb_Aleman.isSelected()) {
                idioma = "Aleman";
            } else if (rb_Español.isSelected()) {
                idioma = "Español";
            } else if (rb_Ingles.isSelected()) {
                idioma = "Ingles";
            } else if (rb_Frances.isSelected()) {
                idioma = "Frances";
            } else {
                idioma = "";
            }//Fin del if del idioma de la serie

            //If de la categoria de la serie
            if (rb_Sitcom.isSelected()) {
                categoria = "Sitcom";
            } else if (rb_YYY.isSelected()) {
                categoria = "YYY";
            } else if (rb_Novelas.isSelected()) {
                categoria = "Novelas";
            } else if (rb_Drama.isSelected()) {
                categoria = "Drama";
            } else if (rb_Suspenso.isSelected()) {
                categoria = "Suspenso";
            } else {
                categoria = "";
            }

            //If del doblaje
            if (rb_Doblaje_No.isSelected()) {
                doblaje = "No";
            } else if (rb_Doblaje_Si.isSelected()) {
                doblaje = "Si";
            } else {
                doblaje = "";
            }//Fin del if del doblaje de la serie

            //If de los subtitulos de la serie
            if (rb_Subtitulos_Si.isSelected()) {
                subtitulos = "Si";
            } else if (rb_Subtitulos_No.isSelected()) {
                subtitulos = "No";
            } else {
                subtitulos = "";
            }//Fin del if de los subtitulos

            //Llenado el resto de los datos
            nombre = tf_Nombre_Serie.getText();
            duracion = Integer.parseInt(tf_Duracion_Serie.getText());
            actores.add(ta_Arctores_Series.getText());
            temporadoas = Integer.parseInt(tf_Temporada.getText());
            productora = tf_Productora_Serie.getText();
            s = new Series(nombre, duracion, categoria, temporadoas, productora, idioma, doblaje, subtitulos);
            s.getActores().add(actores);
            ap.getListap().add(s);
            ap.escribirArchivo();
        } catch (IOException e) {
        }

        //Reseteando los valores de los textos
        tf_Duracion_Serie.setText("");
        tf_Nombre_Serie.setText("");
        tf_Productora_Serie.setText("");
        tf_Temporada.setText("");
        ta_Arctores_Series.setText("");
        rb_Aleman.setSelected(false);
        rb_Doblaje_No.setSelected(false);
        rb_Doblaje_Si.setSelected(false);
        rb_Drama.setSelected(false);
        rb_Español.setSelected(false);
        rb_Frances.setSelected(false);
        rb_Ingles.setSelected(false);
        rb_Novelas.setSelected(false);
        rb_Sitcom.setSelected(false);
        rb_Subtitulos_No.setSelected(false);
        rb_Subtitulos_Si.setSelected(false);
        rb_Suspenso.setSelected(false);
        rb_YYY.setSelected(false);
    }//GEN-LAST:event_bt_Crear_GuardarActionPerformed

    private void bt_Crear_SerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_SerieActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String nombre;
        int duracion;
        String categoria;
        ArrayList actores = new ArrayList();
        int temporadoas;
        String productora;
        String idioma;
        String doblaje;
        String subtitulos;

        //If de los idiomas
        if (rb_Aleman.isSelected()) {
            idioma = "Aleman";
        } else if (rb_Español.isSelected()) {
            idioma = "Español";
        } else if (rb_Ingles.isSelected()) {
            idioma = "Ingles";
        } else if (rb_Frances.isSelected()) {
            idioma = "Frances";
        } else {
            idioma = "";
        }//Fin del if del idioma de la serie

        //If de la categoria de la serie
        if (rb_Sitcom.isSelected()) {
            categoria = "Sitcom";
        } else if (rb_YYY.isSelected()) {
            categoria = "YYY";
        } else if (rb_Novelas.isSelected()) {
            categoria = "Novelas";
        } else if (rb_Drama.isSelected()) {
            categoria = "Drama";
        } else if (rb_Suspenso.isSelected()) {
            categoria = "Suspenso";
        } else {
            categoria = "";
        }

        //If del doblaje
        if (rb_Doblaje_No.isSelected()) {
            doblaje = "No";
        } else if (rb_Doblaje_Si.isSelected()) {
            doblaje = "Si";
        } else {
            doblaje = "";
        }//Fin del if del doblaje de la serie

        //If de los subtitulos de la serie
        if (rb_Subtitulos_Si.isSelected()) {
            subtitulos = "Si";
        } else if (rb_Subtitulos_No.isSelected()) {
            subtitulos = "No";
        } else {
            subtitulos = "";
        }//Fin del if de los subtitulos

        //Llenado el resto de los datos
        nombre = tf_Nombre_Serie.getText();
        duracion = Integer.parseInt(tf_Duracion_Serie.getText());
        actores.add(ta_Arctores_Series.getText());
        temporadoas = Integer.parseInt(tf_Temporada.getText());
        productora = tf_Productora_Serie.getText();
        s = new Series(nombre, duracion, categoria, temporadoas, productora, idioma, doblaje, subtitulos);
        series.add(s);

        //Reseteando los valores de los textos
        tf_Duracion_Serie.setText("");
        tf_Nombre_Serie.setText("");
        tf_Productora_Serie.setText("");
        tf_Temporada.setText("");
        ta_Arctores_Series.setText("");
        rb_Aleman.setSelected(false);
        rb_Doblaje_No.setSelected(false);
        rb_Doblaje_Si.setSelected(false);
        rb_Drama.setSelected(false);
        rb_Español.setSelected(false);
        rb_Frances.setSelected(false);
        rb_Ingles.setSelected(false);
        rb_Novelas.setSelected(false);
        rb_Sitcom.setSelected(false);
        rb_Subtitulos_No.setSelected(false);
        rb_Subtitulos_Si.setSelected(false);
        rb_Suspenso.setSelected(false);
        rb_YYY.setSelected(false);
    }//GEN-LAST:event_bt_Crear_SerieActionPerformed

    private void jmi_Crear_SerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_Crear_SerieActionPerformed
        // TODO add your handling code here:
        Date f = new Date();
        jd_Crear_Serie.setModal(true);
        jd_Crear_Serie.pack();
        jd_Crear_Serie.setLocationRelativeTo(this);
        jd_Crear_Serie.setVisible(true);
        bitacora += "Crear Serie" + "" + f;
    }//GEN-LAST:event_jmi_Crear_SerieActionPerformed

    private void bt_Crear_Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_Guardar1ActionPerformed
        // TODO add your handling code here:
        try {
            ADMP ap = new ADMP("LAB-6-JasonDeras\\lab6\\Nesflis\\Peliculas");
            ap.cargarArchivo();
            String nombre;
            int duracion;
            String categoria;
            ArrayList actores = new ArrayList();
            String director;
            String productora;
            String idioma;
            String subtitulos;
            String doblaje;

            //If de los idiomas
            if (rb_Aleman1.isSelected()) {
                idioma = "Aleman";
            } else if (rb_Español1.isSelected()) {
                idioma = "Español";
            } else if (rb_Ingles1.isSelected()) {
                idioma = "Ingles";
            } else if (rb_Frances1.isSelected()) {
                idioma = "Frances";
            } else {
                idioma = "";
            }//Fin del if del idioma de la Pelicula

            //If de la categoria de la Pelicula
            if (rb_Animacion.isSelected()) {
                categoria = "Animacion";
            } else if (rb_Fantacsia.isSelected()) {
                categoria = "Fantasia";
            } else if (rb_Suspenso1.isSelected()) {
                categoria = "Suspenso";
            } else if (rb_Terror.isSelected()) {
                categoria = "Terror";
            } else if (rb_Accion.isSelected()) {
                categoria = "Accion";
            } else if (rb_Romanticas.isSelected()) {
                categoria = "Romanticas";
            } else if (rb_Ciencia_Ficcion.isSelected()) {
                categoria = "Ciencia Ficcion";
            } else {
                categoria = "";
            }//Fin del if de la categoria de las peliculas

            //If del doblaje
            if (rb_Doblaje_No.isSelected()) {
                doblaje = "No";
            } else if (rb_Doblaje_Si.isSelected()) {
                doblaje = "Si";
            } else {
                doblaje = "";
            }//Fin del if del doblaje de la serie

            //If de los subtitulos de la serie
            if (rb_Subtitulos_Si.isSelected()) {
                subtitulos = "Si";
            } else if (rb_Subtitulos_No.isSelected()) {
                subtitulos = "No";
            } else {
                subtitulos = "";
            }//Fin del if de los subtitulos

            //Llenado el resto de los datos
            nombre = tf_Nombre_Pelicula.getText();
            duracion = Integer.parseInt(tf_Duracion_Pelicula.getText());
            actores.add(ta_Arctores_Peliculas.getText());
            director = tf_Director.getText();
            productora = tf_Productora_Pelicula.getText();
            p = new Peliculas(nombre, duracion, categoria, director, productora, idioma, subtitulos, doblaje);
            p.getActores().add(actores);
            ap.getListap().add(p);
            ap.escribirArchivo();
        } catch (IOException e) {
        }

        //Reseteando los valores de los textos
        tf_Duracion_Pelicula.setText("");
        tf_Nombre_Pelicula.setText("");
        tf_Productora_Pelicula.setText("");
        tf_Director.setText("");
        ta_Arctores_Peliculas.setText("");
        rb_Aleman1.setSelected(false);
        rb_Doblaje_No1.setSelected(false);
        rb_Doblaje_Si1.setSelected(false);
        rb_Accion.setSelected(false);
        rb_Español1.setSelected(false);
        rb_Frances1.setSelected(false);
        rb_Ingles1.setSelected(false);
        rb_Romanticas.setSelected(false);
        rb_Terror.setSelected(false);
        rb_Subtitulos_No1.setSelected(false);
        rb_Subtitulos_Si1.setSelected(false);
        rb_Suspenso1.setSelected(false);
        rb_Ciencia_Ficcion.setSelected(false);
    }//GEN-LAST:event_bt_Crear_Guardar1ActionPerformed

    private void bt_Crear_PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_PeliculaActionPerformed
        // TODO add your handling code here:
        String nombre;
        int duracion;
        String categoria;
        ArrayList actores = new ArrayList();
        String director;
        String productora;
        String idioma;
        String subtitulos;
        String doblaje;

        //If de los idiomas
        if (rb_Aleman1.isSelected()) {
            idioma = "Aleman";
        } else if (rb_Español1.isSelected()) {
            idioma = "Español";
        } else if (rb_Ingles1.isSelected()) {
            idioma = "Ingles";
        } else if (rb_Frances1.isSelected()) {
            idioma = "Frances";
        } else {
            idioma = "";
        }//Fin del if del idioma de la Pelicula

        //If de la categoria de la Pelicula
        if (rb_Animacion.isSelected()) {
            categoria = "Animacion";
        } else if (rb_Fantacsia.isSelected()) {
            categoria = "Fantasia";
        } else if (rb_Suspenso1.isSelected()) {
            categoria = "Suspenso";
        } else if (rb_Terror.isSelected()) {
            categoria = "Terror";
        } else if (rb_Accion.isSelected()) {
            categoria = "Accion";
        } else if (rb_Romanticas.isSelected()) {
            categoria = "Romanticas";
        } else if (rb_Ciencia_Ficcion.isSelected()) {
            categoria = "Ciencia Ficcion";
        } else {
            categoria = "";
        }//Fin del if de la categoria de las peliculas

        //If del doblaje
        if (rb_Doblaje_No.isSelected()) {
            doblaje = "No";
        } else if (rb_Doblaje_Si.isSelected()) {
            doblaje = "Si";
        } else {
            doblaje = "";
        }//Fin del if del doblaje de la serie

        //If de los subtitulos de la serie
        if (rb_Subtitulos_Si.isSelected()) {
            subtitulos = "Si";
        } else if (rb_Subtitulos_No.isSelected()) {
            subtitulos = "No";
        } else {
            subtitulos = "";
        }//Fin del if de los subtitulos

        //Llenado el resto de los datos
        nombre = tf_Nombre_Pelicula.getText();
        duracion = Integer.parseInt(tf_Duracion_Pelicula.getText());
        actores.add(ta_Arctores_Peliculas.getText());
        director = tf_Director.getText();
        productora = tf_Productora_Pelicula.getText();
        p = new Peliculas(nombre, duracion, categoria, director, productora, idioma, subtitulos, doblaje);
        p.getActores().add(actores);

        //Reseteando los valores de los textos
        tf_Duracion_Pelicula.setText("");
        tf_Nombre_Pelicula.setText("");
        tf_Productora_Pelicula.setText("");
        tf_Director.setText("");
        ta_Arctores_Peliculas.setText("");
        rb_Aleman1.setSelected(false);
        rb_Doblaje_No1.setSelected(false);
        rb_Doblaje_Si1.setSelected(false);
        rb_Accion.setSelected(false);
        rb_Español1.setSelected(false);
        rb_Frances1.setSelected(false);
        rb_Ingles1.setSelected(false);
        rb_Romanticas.setSelected(false);
        rb_Terror.setSelected(false);
        rb_Subtitulos_No1.setSelected(false);
        rb_Subtitulos_Si1.setSelected(false);
        rb_Suspenso1.setSelected(false);
        rb_Ciencia_Ficcion.setSelected(false);
    }//GEN-LAST:event_bt_Crear_PeliculaActionPerformed

    private void jmi_Crear_PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_Crear_PeliculaActionPerformed
        // TODO add your handling code here:
        Date f = new Date();
        jd_Crear_Pelicula.setModal(true);
        jd_Crear_Pelicula.pack();
        jd_Crear_Pelicula.setLocationRelativeTo(this);
        jd_Crear_Pelicula.setVisible(true);
        bitacora += "Crear Serie" + "" + f;
    }//GEN-LAST:event_jmi_Crear_PeliculaActionPerformed

    private void bt_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CargarActionPerformed
        // TODO add your handling code here:
        ADMP ap = new ADMP("LAB-6-JasonDeras\\lab6\\Nesflis\\Peliculas");
        AMDS as = new AMDS("LAB-6-JasonDeras\\lab6\\Nesflis\\Series");
        DefaultTreeModel m = (DefaultTreeModel) jt_Catalogo.getModel();

        File f = new File("./Nesflis");
        m.setRoot(new DefaultMutableTreeNode(f.getName()));
        listar(f, (DefaultMutableTreeNode) m.getRoot());

        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        for (Peliculas p : ap.getListap()) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(p.getNombre());
            if (p.getCategoria().equals("Suspenso")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (p.getCategoria().equals("Terror")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (p.getCategoria().equals("Accion")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (p.getCategoria().equals("Romanticas")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (p.getCategoria().equals("Ciencia Ficcion")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (p.getCategoria().equals("Animacion")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (p.getCategoria().equals("Fantasia")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            }//Fin del if que organiza las peliculas
        }//Fin del for de las peliculas

        for (Series s : as.getListap()) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(p.getNombre());
            if (s.getCategoria().equals("Sitcom")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (s.getCategoria().equals("Drama")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (s.getCategoria().equals("Novelas")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (s.getCategoria().equals("Suspenso")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            } else if (s.getCategoria().equals("YYY")) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).add(n);
            }//Fin del if de las series
        }//Fin del for de las series

    }//GEN-LAST:event_bt_CargarActionPerformed

    private void jmi_Listar_ArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_Listar_ArbolActionPerformed
        // TODO add your handling code here:
        jd_Listar.setModal(true);
        jd_Listar.pack();
        jd_Listar.setLocationRelativeTo(this);
        jd_Listar.setVisible(true);
    }//GEN-LAST:event_jmi_Listar_ArbolActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    public void listar(File p_raiz, DefaultMutableTreeNode nodo) {
        try {
            for (File temp : p_raiz.listFiles()) {
                if (temp.isFile()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getName());
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getName());
                    nodo.add(n);
                    listar(temp, n);
                }

            }
        } catch (Exception e) {
        }
    }

    public void bitacora(String bitacora) throws IOException {
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File("./Bitacora.txt");
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            bw.write(bitacora);
            bw.newLine();
        } catch (Exception e) {
            e.printStackTrace();
        }
        bw.close();
        fw.close();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Categoria_Pelicula;
    private javax.swing.ButtonGroup bg_Categoria_Serie;
    private javax.swing.ButtonGroup bg_Doblaje_Pelicula;
    private javax.swing.ButtonGroup bg_Doblaje_Serie;
    private javax.swing.ButtonGroup bg_Idioma_Pelicula;
    private javax.swing.ButtonGroup bg_Idioma_Serie;
    private javax.swing.ButtonGroup bg_Subtitulado_Pelicula;
    private javax.swing.ButtonGroup bg_Subtitulo_Serie;
    private javax.swing.JButton bt_Cargar;
    private javax.swing.JButton bt_Crear_Guardar;
    private javax.swing.JButton bt_Crear_Guardar1;
    private javax.swing.JButton bt_Crear_Pelicula;
    private javax.swing.JButton bt_Crear_Serie;
    private javax.swing.JButton bt_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_Crear_Pelicula;
    private javax.swing.JDialog jd_Crear_Serie;
    private javax.swing.JDialog jd_Listar;
    private javax.swing.JDialog jd_Login;
    private javax.swing.JMenu jm_Accerder;
    private javax.swing.JMenu jm_Listar;
    private javax.swing.JMenu jm_Peliculas;
    private javax.swing.JMenu jm_Series;
    private javax.swing.JMenuBar jmb_Opciones;
    private javax.swing.JMenuItem jmi_Crear_Pelicula;
    private javax.swing.JMenuItem jmi_Crear_Serie;
    private javax.swing.JMenuItem jmi_Listar_Arbol;
    private javax.swing.JMenuItem jmi_Login;
    private javax.swing.JMenuItem jmi_Logout;
    private javax.swing.JTree jt_Catalogo;
    private javax.swing.JPasswordField pf_Clave_Usuario;
    private javax.swing.JRadioButton rb_Accion;
    private javax.swing.JRadioButton rb_Aleman;
    private javax.swing.JRadioButton rb_Aleman1;
    private javax.swing.JRadioButton rb_Animacion;
    private javax.swing.JRadioButton rb_Ciencia_Ficcion;
    private javax.swing.JRadioButton rb_Doblaje_No;
    private javax.swing.JRadioButton rb_Doblaje_No1;
    private javax.swing.JRadioButton rb_Doblaje_Si;
    private javax.swing.JRadioButton rb_Doblaje_Si1;
    private javax.swing.JRadioButton rb_Drama;
    private javax.swing.JRadioButton rb_Español;
    private javax.swing.JRadioButton rb_Español1;
    private javax.swing.JRadioButton rb_Fantacsia;
    private javax.swing.JRadioButton rb_Frances;
    private javax.swing.JRadioButton rb_Frances1;
    private javax.swing.JRadioButton rb_Ingles;
    private javax.swing.JRadioButton rb_Ingles1;
    private javax.swing.JRadioButton rb_Novelas;
    private javax.swing.JRadioButton rb_Romanticas;
    private javax.swing.JRadioButton rb_Sitcom;
    private javax.swing.JRadioButton rb_Subtitulos_No;
    private javax.swing.JRadioButton rb_Subtitulos_No1;
    private javax.swing.JRadioButton rb_Subtitulos_Si;
    private javax.swing.JRadioButton rb_Subtitulos_Si1;
    private javax.swing.JRadioButton rb_Suspenso;
    private javax.swing.JRadioButton rb_Suspenso1;
    private javax.swing.JRadioButton rb_Terror;
    private javax.swing.JRadioButton rb_YYY;
    private javax.swing.JTextArea ta_Arctores_Peliculas;
    private javax.swing.JTextArea ta_Arctores_Series;
    private javax.swing.JTextField tf_Director;
    private javax.swing.JTextField tf_Duracion_Pelicula;
    private javax.swing.JTextField tf_Duracion_Serie;
    private javax.swing.JTextField tf_Nombre_Pelicula;
    private javax.swing.JTextField tf_Nombre_Serie;
    private javax.swing.JTextField tf_Productora_Pelicula;
    private javax.swing.JTextField tf_Productora_Serie;
    private javax.swing.JTextField tf_Temporada;
    private javax.swing.JTextField tf_Usuario;
    // End of variables declaration//GEN-END:variables
    Peliculas p;
    Series s;
    ArrayList series = new ArrayList();
    ArrayList Peliculas = new ArrayList();
    String bitacora = "";
}
